name: push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: make app-test
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: roberto345/devops-for-programmers-project-74:latest
